### ISSUE TITLE
SRS Task List

### ISSUE THREAD

**Issue by Wyvernix** [ionicsoft/vidon#25]
These are the requirements listed in the SRS. Please comment or create a PR to claim a task.

### Major tasks
- [x] Movie rentals (See #26)
- [x] Payment management/processing
  - [x] Decide if using mock or [real](https://stripe.com/docs/api?lang=ruby) [api](https://stripe.com/docs/checkout/rails)
  - [x] Failed payments
- [x] Publisher user logic
- [x] Authorization to restrict access to pages and actions
- [x] Email system
- [x] Content recommendation logic for homepage
- [x] Video playback save/resume
- [x] UI/UX design (See #27, #34 )
  - [x] Navigation flow

### Moderate tasks
- [x] Add favorites infrastructure
- [x] Add comments to video pages (See #27)
- [x] Add search filters (See #20)
- [x] Purchase additional slots
- [x] Publisher sign up page?
- [x] [Publisher] Create content pages (movie or show overview)
- [x] [Publisher] Create episode pages
- [x] [Publisher] Upload videos
- [x] Video autoplay next video in series
- [x] Configure genres and actors

### Minor tasks
- [x] Publisher has access to the user ratings and comments on their own content.
  - Provide way to view these things
- [x] Add ratings to show pages (See #27)
- [x] Add favorites buttons
- [x] Add email reminder to daily task ```renew == today + 5.days```
- [ ] [Publisher] Set cost of episodes/movies as free
  - Might skip this; leave until last

**Comment by SRHarrison13** [comment]
I'll work on the stuff for Publishers.

**Comment by Wyvernix** [comment]
Going to be working on authorization and persistent authentication.

**Comment by Wyvernix** [comment]
Starting to work on video autoplay

**Comment by Wyvernix** [comment]
I'm working on search filters. I will work on content recommendation next. I'm probably going to add a model for viewing history to keep track of last watched video as well as recommendation logic. This model could also be used to store the current_time value needed for the video save/resume feature.
